In [ ]:
from google.colab import drive
drive.mount('/content/drive')
exec(open("/content/drive/MyDrive/imdb_peft_project/code/lora-imdb-classifier/00_colab_setup.py").read())

Mounted at /content/drive
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✓ /content/drive/MyDrive/imdb_peft_project
✓ /content/drive/MyDrive/imdb_peft_project/checkpoints/roberta_lora
✓ /content/drive/MyDrive/imdb_peft_project/checkpoints/deberta_lora
✓ /content/drive/MyDrive/imdb_peft_project/oof_predictions
✓ /content/drive/MyDrive/imdb_peft_project/results
✓ /content/drive/MyDrive/imdb_peft_project/notebooks
✓ /content/drive/MyDrive/imdb_peft_project/code

Folder structure ready.
Enter GitHub Token: ··········
Repository exists, pulling latest changes...
✓ Pull complete.

Repository path: /content/drive/MyDrive/imdb_peft_project/code/lora-imdb-classifier
==================================================
SETUP COMPLETE
==================================================
Drive folder  : /content/drive/MyDrive/imdb_peft_project
GitHub repo   : /content/drive/MyDrive/imdb_peft_project/code/lora-imdb-classifier

Available functions:
  push_to_github('message')        → push code to GitHub
  save_code_to_repo('file.py')     → copy .py file to repository
  save_oof(preds, 'roberta', 0)    → save OOF predictions
  load_oof('roberta')              → load OOF predictions
  save_results(metrics)            → save evaluation results

In [ ]:
!pip install transformers peft accelerate torchao --upgrade -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 151.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.2/389.2 kB 41.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 131.4 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import numpy as np
import torch
import time
import os
from transformers import (DebertaV2Tokenizer, DebertaV2ForSequenceClassification,
                          TrainingArguments, Trainer, TrainerCallback)
from peft import LoraConfig, get_peft_model, TaskType
from torch.utils.data import Dataset
from sklearn.metrics import (accuracy_score, f1_score,
                             precision_score, recall_score, roc_auc_score)

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so

Device: cuda

In [ ]:
# Ablation results folder
DIRS["ablation"] = f"{DIRS['root']}/ablation_results"
os.makedirs(DIRS["ablation"], exist_ok=True)

# Load data
train_df = pd.read_parquet(f"{DIRS['root']}/train_df_v2.parquet")
test_df  = pd.read_parquet(f"{DIRS['root']}/test_df_v2.parquet")
print(f"Train: {len(train_df)} | Test: {len(test_df)}")

Train: 25000 | Test: 25000

In [ ]:
def head_tail_truncate_v2(text, tokenizer, max_len=512, head_len=256):
    """V2: Equal split — first 256 + last 256 tokens."""
    tail_len = max_len - head_len
    tokens = tokenizer(text, add_special_tokens=False,
                       truncation=False, return_tensors=None)
    input_ids      = tokens["input_ids"]
    attention_mask = tokens["attention_mask"]
    if len(input_ids) > max_len - 2:
        input_ids      = input_ids[:head_len] + input_ids[-tail_len:]
        attention_mask = attention_mask[:head_len] + attention_mask[-tail_len:]
    return tokenizer(
        tokenizer.decode(input_ids),
        max_length=max_len,
        padding="max_length",
        truncation=True,
        return_tensors=None
    )

class IMDBDataset(Dataset):
    def __init__(self, df, tokenizer, max_len=512, head_len=256):
        self.df        = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_len   = max_len
        self.head_len  = head_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        text  = self.df.loc[idx, "text_clean"]
        label = self.df.loc[idx, "label"]
        encoding = head_tail_truncate_v2(
            text, self.tokenizer, self.max_len, self.head_len
        )
        return {
            "input_ids":      torch.tensor(encoding["input_ids"],      dtype=torch.long),
            "attention_mask": torch.tensor(encoding["attention_mask"], dtype=torch.long),
            "labels":         torch.tensor(label,                      dtype=torch.long),
        }

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    probs = torch.softmax(torch.tensor(logits), dim=-1)[:, 1].numpy()
    return {
        "accuracy" : accuracy_score(labels, preds),
        "f1"       : f1_score(labels, preds),
        "precision": precision_score(labels, preds),
        "recall"   : recall_score(labels, preds),
        "roc_auc"  : roc_auc_score(labels, probs)
    }

print("Loading DeBERTa tokenizer...")
tokenizer     = DebertaV2Tokenizer.from_pretrained("microsoft/deberta-v3-base")
train_dataset = IMDBDataset(train_df, tokenizer)
test_dataset  = IMDBDataset(test_df,  tokenizer)
print(f"✓ Train: {len(train_dataset)} — Test: {len(test_dataset)}")

Loading DeBERTa tokenizer...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

✓ Train: 25000 — Test: 25000

In [ ]:
class SaveCallbackFixed(TrainerCallback):
    def on_epoch_end(self, args, state, control, **kwargs):
        epoch = int(state.epoch)
        save_path = f"{args.output_dir}/epoch_{epoch}"
        os.makedirs(save_path, exist_ok=True)
        kwargs["model"].save_pretrained(save_path)
        extra_state = {
            "classifier.weight": kwargs["model"].base_model.model.classifier.weight.data.cpu(),
            "classifier.bias"  : kwargs["model"].base_model.model.classifier.bias.data.cpu(),
            "pooler.weight"    : kwargs["model"].base_model.model.pooler.dense.weight.data.cpu(),
            "pooler.bias"      : kwargs["model"].base_model.model.pooler.dense.bias.data.cpu(),
        }
        torch.save(extra_state, f"{save_path}/extra_weights.pt")

def train_deberta_config(config_name, r, lr, warmup_steps=500,
                         weight_decay=0.01, grad_accum=2, epochs=3):
    """Train DeBERTa with specific hyperparameters."""
    print(f"\n{'='*50}")
    print(f"Config: {config_name} | r={r} | lr={lr}")
    print(f"{'='*50}")

    output_dir = f"{DIRS['ablation']}/deberta_{config_name}"
    os.makedirs(output_dir, exist_ok=True)

    base_model = DebertaV2ForSequenceClassification.from_pretrained(
        "microsoft/deberta-v3-base",
        num_labels=2,
        torch_dtype=torch.float32
    )

    lora_config = LoraConfig(
        task_type=TaskType.SEQ_CLS,
        r=r,
        lora_alpha=r * 2,
        lora_dropout=0.1,
        target_modules=["query_proj", "value_proj"],
        bias="none"
    )

    model = get_peft_model(base_model, lora_config)
    model = model.to(torch.float32).to(device)
    model.print_trainable_parameters()

    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=epochs,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=16,
        learning_rate=lr,
        warmup_steps=warmup_steps,
        weight_decay=weight_decay,
        gradient_accumulation_steps=grad_accum,
        eval_strategy="epoch",
        save_strategy="no",
        fp16=False,
        bf16=False,
        seed=SEED,
        report_to="none"
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        compute_metrics=compute_metrics,
        callbacks=[SaveCallbackFixed()]
    )

    start = time.time()
    trainer.train()
    train_time = time.time() - start

    metrics = trainer.evaluate()
    results = {
        "config"             : config_name,
        "r"                  : r,
        "lr"                 : lr,
        "trainable_params"   : sum(p.numel() for p in model.parameters() if p.requires_grad),
        "accuracy"           : round(metrics["eval_accuracy"], 4),
        "f1"                 : round(metrics["eval_f1"], 4),
        "precision"          : round(metrics["eval_precision"], 4),
        "recall"             : round(metrics["eval_recall"], 4),
        "roc_auc"            : round(metrics["eval_roc_auc"], 4),
        "train_time_minutes" : round(train_time / 60, 1),
    }

    print(f"\n✓ {config_name} complete:")
    print(f"  Accuracy : {results['accuracy']}")
    print(f"  F1       : {results['f1']}")
    print(f"  Time     : {results['train_time_minutes']} minutes")

    save_results(results, f"ablation_deberta_{config_name}.json")

    del model, trainer, base_model
    torch.cuda.empty_cache()

    return results

print("✓ DeBERTa training function ready.")

✓ DeBERTa training function ready.

In [ ]:
deberta_results = []

# Config 1: baseline (mevcut) — manuel ekle
config1 = {
    "config"           : "r16_lr3e5",
    "r"                : 16,
    "lr"               : 3e-5,
    "trainable_params" : 591362,
    "accuracy"         : 0.9536,
    "f1"               : 0.9540,
    "precision"        : 0.9474,
    "recall"           : 0.9606,
    "roc_auc"          : 0.9890,
    "train_time_minutes": 49.3,
}
deberta_results.append(config1)
print("✓ Config 1 (r=16, lr=3e-5) added from existing results.")

# Config 2: higher lr
res2 = train_deberta_config("r16_lr5e5", r=16, lr=5e-5)
deberta_results.append(res2)

# Config 3: higher rank
res3 = train_deberta_config("r32_lr3e5", r=32, lr=3e-5)
deberta_results.append(res3)

# Config 4: higher rank + higher lr
res4 = train_deberta_config("r32_lr5e5", r=32, lr=5e-5)
deberta_results.append(res4)

# Print comparison table
import pandas as pd
df = pd.DataFrame(deberta_results)
print(f"\n{'='*70}")
print("DEBERTA HYPERPARAMETER SEARCH RESULTS")
print(f"{'='*70}")
print(df[["config", "r", "lr", "accuracy", "f1", "roc_auc",
          "train_time_minutes"]].to_string(index=False))

save_results({"deberta_ablation": deberta_results},
             "ablation_deberta_all.json")

✓ Config 1 (r=16, lr=3e-5) added from existing results.

==================================================
Config: r16_lr5e5 | r=16 | lr=5e-05
==================================================

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/371M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

[transformers] DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.classifier.weight      | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
pooler.dense.weight                     | MISSING    |
classifier.bias                         | MISSING    |
pooler.dense.bias                       | MISSING    |
classifier.weight                       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

trainable params: 591,362 || all params: 185,015,044 || trainable%: 0.3196

[transformers] `use_return_dict` is deprecated! Use `return_dict` instead!

model.safetensors:   0%|          | 0.00/371M [00:00<?, ?B/s]

✓ r16_lr5e5 complete:
  Accuracy : 0.9571
  F1       : 0.9574
  Time     : 50.1 minutes
✓ Results saved: /content/drive/MyDrive/imdb_peft_project/results/ablation_deberta_r16_lr5e5.json

==================================================
Config: r32_lr3e5 | r=32 | lr=3e-05
==================================================

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

[transformers] DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.classifier.weight      | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
pooler.dense.weight                     | MISSING    |
classifier.bias                         | MISSING    |
pooler.dense.bias                       | MISSING    |
classifier.weight                       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

trainable params: 1,181,186 || all params: 185,604,868 || trainable%: 0.6364

✓ r32_lr3e5 complete:
  Accuracy : 0.9579
  F1       : 0.9581
  Time     : 50.1 minutes
✓ Results saved: /content/drive/MyDrive/imdb_peft_project/results/ablation_deberta_r32_lr3e5.json

==================================================
Config: r32_lr5e5 | r=32 | lr=5e-05
==================================================

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

[transformers] DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.classifier.weight      | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
pooler.dense.weight                     | MISSING    |
classifier.bias                         | MISSING    |
pooler.dense.bias                       | MISSING    |
classifier.weight                       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

trainable params: 1,181,186 || all params: 185,604,868 || trainable%: 0.6364

✓ r32_lr5e5 complete:
  Accuracy : 0.9602
  F1       : 0.9605
  Time     : 50.1 minutes
✓ Results saved: /content/drive/MyDrive/imdb_peft_project/results/ablation_deberta_r32_lr5e5.json

======================================================================
DEBERTA HYPERPARAMETER SEARCH RESULTS
======================================================================
   config  r      lr  accuracy     f1  roc_auc  train_time_minutes
r16_lr3e5 16 0.00003    0.9536 0.9540   0.9890                49.3
r16_lr5e5 16 0.00005    0.9571 0.9574   0.9905                50.1
r32_lr3e5 32 0.00003    0.9579 0.9581   0.9906                50.1
r32_lr5e5 32 0.00005    0.9602 0.9605   0.9915                50.1
✓ Results saved: /content/drive/MyDrive/imdb_peft_project/results/ablation_deberta_all.json

In [ ]:
NOTEBOOK_NAME = "ablation_deberta_hyperparams"

!jupyter nbconvert --to script \
  "/content/drive/MyDrive/Colab Notebooks/{NOTEBOOK_NAME}.ipynb" \
  --output-dir "/content/"

import os
os.rename(f"/content/{NOTEBOOK_NAME}.txt",
          f"/content/{NOTEBOOK_NAME}.py")

save_code_to_repo(f"/content/{NOTEBOOK_NAME}.py")
push_to_github("deberta hyperparameter ablation - best r32 lr5e5 acc 0.9602")

[NbConvertApp] Converting notebook /content/drive/MyDrive/Colab Notebooks/ablation_deberta_hyperparams.ipynb to script
[NbConvertApp] ERROR | Notebook JSON is invalid: Additional properties are not allowed ('metadata' was unexpected)

Failed validating 'additionalProperties' in stream:

On instance['cells'][6]['outputs'][0]:
{'metadata': {'tags': None},
 'name': 'stdout',
 'output_type': 'stream',
 'text': '✓ Config 1 (r=16, lr=3e-5) added from existing results.\n'
         '\n'
         '=======...'}
[NbConvertApp] Writing 8198 bytes to /content/ablation_deberta_hyperparams.txt
✓ ablation_deberta_hyperparams.py → copied to repository.
⚠ Error: remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/DenizhanOngun/lora-imdb-classifier.git/'

In [ ]:
import getpass
import subprocess

# Update remote URL with new token
GITHUB_TOKEN = getpass.getpass("GitHub Token: ")
GITHUB_USERNAME = "DenizhanOngun"
GITHUB_REPO = "lora-imdb-classifier"

new_url = f"https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{GITHUB_REPO}.git"
subprocess.run(f"cd {REPO_PATH} && git remote set-url origin '{new_url}'", shell=True)

push_to_github("deberta hyperparameter ablation - best r32 lr5e5 acc 0.9602")

GitHub Token: ··········
ℹ No changes to commit, push skipped.

In [ ]:
import subprocess

subprocess.run(f"cd {REPO_PATH} && git add -f ablation_deberta_hyperparams.py", shell=True)
result = subprocess.run(f"cd {REPO_PATH} && git commit -m 'deberta hyperparameter ablation - best r32 lr5e5 acc 0.9602'",
                       shell=True, capture_output=True, text=True)
print(result.stdout)
subprocess.run(f"cd {REPO_PATH} && git push origin main", shell=True, capture_output=False)

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

CompletedProcess(args='cd /content/drive/MyDrive/imdb_peft_project/code/lora-imdb-classifier && git push origin main', returncode=128)

In [ ]:
import subprocess
import getpass

GITHUB_TOKEN = getpass.getpass("GitHub Token: ")
new_url = f"https://DenizhanOngun:{GITHUB_TOKEN}@github.com/DenizhanOngun/lora-imdb-classifier.git"

subprocess.run(f"cd {REPO_PATH} && git remote set-url origin \"{new_url}\"", shell=True)
result = subprocess.run(f"cd {REPO_PATH} && git push origin main",
                       shell=True, capture_output=True, text=True)
print(result.stdout)
print(result.stderr)

GitHub Token: ··········

To https://github.com/DenizhanOngun/lora-imdb-classifier.git
   504f1f2..d9a9494  main -> main